Repository Team-Inframe/Inframe-Frontend, pull requests merged in 2025-01, with the labels that each got.

#2 [chore] 개발 환경 세팅
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/pre-commit
  .prettierrc
  README.md
  eslint.config.js
  index.html
  jsconfig.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.jsx
  src/api/index.js
  src/assets/react.svg
  src/components/index.jsx
  src/globals.css
  src/hooks/index.js
  src/main.jsx
  src/pages/Main/components/index.jsx
  src/pages/Main/index.jsx
  src/routes/routePath.js
  src/routes/router.jsx
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: 🪄 Chore

#4 [chore] 모바일 고정 뷰 세팅
  README.md
  eslint.config.js
  index.html
  package.json
  src/App.jsx
  src/common/index.jsx
  src/globals.css
  src/libraries/index.jsx
  src/libraries/reactQuery/ReactQuerySetting.jsx
  src/pages/Main/index.jsx
  src/pages/Main/page.jsx
  src/routes/router.jsx
  tailwind.config.js
  yarn.lock
Labels: 🪄 Chore

#6 chore: 파일 구조 변경
  src/componets/Main/index.jsx
  src/componets/common/index.jsx
  src/pages/Main/components/index.jsx
  src/pages/Mypage/page.jsx
Labels: 🪄 Chore

#13 Chore/#11 global envsetting
  .prettierrc
  jsconfig.json
  package.json
  public/Fonts/Pretendard-Bold.otf
  public/Fonts/Pretendard-Light.otf
  public/Fonts/Pretendard-Medium.otf
  src/components/common/IconButton/index.jsx
  src/components/common/index.jsx
  src/components/layout/Footer/index.jsx
  src/components/pages/Main/index.jsx
  src/componets/common/IconButton/index.jsx
  src/globals.css
  src/pages/Main/page.jsx
  tailwind.config.js
  yarn.lock
Labels: 🪄 Chore

#17 [design] 보관함 페이지 퍼블리싱
  src/assets/images/frame1.png
  src/assets/svgs/EmptyFile.svg
  src/assets/svgs/LeftArrow.svg
  src/assets/svgs/RightArrow.svg
  src/components/pages/Storage/EmptyStorage/index.jsx
  src/components/pages/Storage/StorageImages/index.jsx
  src/components/pages/Storage/StorageLayout/index.jsx
  src/components/pages/Storage/StorageMenu/index.jsx
  src/pages/Storage/Gallery/page.jsx
  src/pages/Storage/MyFrame/page.jsx
  src/pages/Storage/SavedFrame/page.jsx
  src/pages/Storage/page.jsx
  src/routes/routePath.js
  src/routes/router.jsx
Labels: 🎨 Design

#18 Feat/#10 mainpage
  public/icons/MoveButton.png
  public/icons/backbutton.png
  public/icons/download.png
  public/icons/frame.png
  src/components/common/DownloudButton/index.jsx
  src/components/common/IconButton/index.jsx
  src/components/layout/Footer/index.jsx
  src/components/layout/Header/index.jsx
  src/components/pages/HotFrame/index.jsx
  src/components/pages/Main/Carousel/index.jsx
  src/components/pages/Main/RecommendCard/index.jsx
  src/globals.css
  src/pages/HotFramePage/page.jsx
  src/pages/Main/page.jsx
  src/pages/SaveHotFrame/page.jsx
  src/routes/routePath.js
  src/routes/router.jsx
Labels: 🎨 Design, 🚀 Feat

#21 Feat/#15 selectframe page
  public/framepic/heightframe1.png
  public/framepic/heightframe2.png
  public/framepic/widthframe1.png
  public/framepic/widthframe2.png
  public/icons/backbutton.png
  src/components/common/TextButton/index.jsx
  src/components/common/index.jsx
  src/components/layout/Footer/index.jsx
  src/components/layout/Header/index.jsx
  src/components/pages/Main/RecommendCard/index.jsx
  src/components/pages/MakeBG/AIBG/index.jsx
  src/components/pages/MakeBG/BasicBG/index.jsx
  src/components/pages/MakeBG/PicBG/index.jsx
  src/components/pages/SelectFrame/ColList/index.jsx
  src/components/pages/SelectFrame/FoundationFrame/index.jsx
  src/components/pages/SelectFrame/RowList/index.jsx
  src/pages/Main/page.jsx
  src/pages/MakeBG/page.jsx
  src/pages/Mypage/page.jsx
  src/pages/SelectFrame/page.jsx
  src/routes/router.jsx
Labels: 🚀 Feat

#23 Feat/#20 make bg page
  package.json
  public/icons/MoveButton.png
  public/icons/backbutton.png
  public/icons/cabinetbutton.png
  public/icons/download.png
  public/icons/frame.png
  public/icons/framemakebutton.png
  public/icons/homebutton.png
  public/icons/mypagebutton.png
  src/assets/Fonts/Pretendard-Bold.otf
  src/assets/Fonts/Pretendard-Light.otf
  src/assets/Fonts/Pretendard-Medium.otf
  src/assets/images/basicframepic/heightframe1.png
  src/assets/images/basicframepic/heightframe2.png
  src/assets/images/basicframepic/widthframe1.png
  src/assets/images/basicframepic/widthframe2.png
  src/assets/svgs/MoveButton.svg
  src/assets/svgs/PicSelect.svg
  src/assets/svgs/cabinetbutton.svg
  src/assets/svgs/download.svg
  src/assets/svgs/framemakebutton.svg
  src/assets/svgs/homebutton.svg
  src/components/common/CompleteButton/index.jsx
  src/components/common/DownloadButton/index.jsx
  src/components/layout/Footer/index.jsx
  src/components/layout/Header/index.jsx
  src/components/pages/HotFrame/index.jsx
  src/components/pages/MakeBG/AIBG/index.jsx
  src/components/pages/MakeBG/BasicBG/index.jsx
  src/components/pages/MakeBG/PicBG/index.jsx
  src/components/pages/MakeBG/SelectedFrame/index.jsx
  src/components/pages/SelectFrame/ColList/index.jsx
  src/components/pages/SelectFrame/RowList/index.jsx
  src/globals.css
  src/pages/Main/page.jsx
  src/pages/MakeBG/page.jsx
  src/pages/SaveHotFrame/page.jsx
  src/routes/router.jsx
  tailwind.config.js
  webpack.config.js
  yarn.lock
Labels: 🎨 Design, 🚀 Feat, 📁 Rename

#27 [deploy] vercel 배포
  src/assets/svgs/CabinetButton.svg
  src/assets/svgs/Download.svg
  src/assets/svgs/FrameMakeButton.svg
  src/assets/svgs/HomeButton.svg
  src/assets/svgs/Homebutton.svg
  src/components/layout/Footer/index.jsx
  src/components/pages/HotFrame/index.jsx
  vercel.json
Labels: 🌎 Deploy

#29 [feat] api 연동 개발
  src/api/customframes.js
  src/api/frames.js
  src/api/index.js
  src/api/photos.js
  src/api/stickers.js
  src/api/users.js
  src/routes/routePath.js
  src/routes/router.jsx
  src/test/BookmarkCustomFrameTestPage.jsx
  src/test/CustomFrameCreateTestPage.jsx
  src/test/CustomFrameListTestPage.jsx
  src/test/CustomFrameReadTestPage.jsx
  src/test/FrameBackgroundCreateTestPage.jsx
  src/test/FrameCreateTestPage.jsx
  src/test/FrameViewTestPage.jsx
  src/test/MyBookmarkCustomFrameTestPage.jsx
  src/test/MyCustomFramesPageTest.jsx
  src/test/PhotoCreateTestPage.jsx
  src/test/PhotoListTestPage.jsx
  src/test/StickersTestPage.jsx
  src/test/TestPages.jsx
  src/test/UsersTestPage.jsx
  yarn.lock
Labels: 🚀 Feat

#30 Feat/#24 make sticker
  src/assets/svgs/Homebutton.svg
  src/assets/svgs/sendbutton.svg
  src/components/layout/Footer/index.jsx
  src/components/pages/MakeBG/BasicBG/index.jsx
  src/components/pages/MakeSticker/AISticker/index.jsx
  src/components/pages/MakeSticker/PicSticker/index.jsx
  src/components/pages/SaveFrame/ShareToggle/index.jsx
  src/pages/MakeBG/page.jsx
  src/pages/MakeSticker/page.jsx
  src/pages/SaveFrame/page.jsx
  src/pages/Storage/page.jsx
  src/routes/routePath.js
  src/routes/router.jsx
Labels: 🚀 Feat

#40 [feat] 핫한 프레임 북마크 순 api 연동
  src/api/customframes.js
  src/pages/HotFramePage/page.jsx
Labels: 🚀 Feat

#43 [feat] 초기 프레임 저장 api 연동
  package.json
  src/api/frames.js
  src/api/index.js
  src/libraries/constants/FrameData.js
  src/pages/FrameCreate/Background/page.jsx
  src/pages/FrameCreate/page.jsx
  src/routes/router.jsx
  src/test/FrameBackgroundCreateTestPage.jsx
  src/test/FrameCreateTestPage.jsx
  yarn.lock
Labels: 🚀 Feat

#46 [feat] PWA 적용
  index.html
  package.json
  public/icons/android-icon-192x192.png
  public/icons/apple-icon-114x114.png
  public/icons/apple-icon-152x152.png
  public/icons/apple-icon-180x180.png
  public/icons/apple-icon-60x60.png
  public/icons/apple-icon.png
  public/icons/apple-touch-icon.png
  public/icons/favicon-16x16.ico
  public/icons/favicon-32x32.ico
  public/icons/favicon-96x96.png
  public/icons/favicon.ico
  public/icons/favicon.svg
  public/icons/logo.svg
  public/icons/maskable-icon.png
  public/icons/ms-icon-144x144.png
  public/icons/ms-icon-150x150.png
  public/icons/ms-icon-310x310.png
  public/icons/ms-icon-70x70.png
  public/icons/web-app-manifest-192x192.png
  public/icons/web-app-manifest-512x512.png
  public/manifest.json
  public/service-worker.js
  public/splash_screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
  public/splash_screens/iPhone_11_Pro_Max__iPhone_XS_Max_portrait.png
  public/splash_screens/iPhone_11__iPhone_XR_portrait.png
  public/splash_screens/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait.png
  public/splash_screens/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait.png
  public/splash_screens/iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait.png
  public/splash_screens/iPhone_16_Plus__iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_portrait.png
  public/splash_screens/iPhone_16_Pro_Max_portrait.png
  public/splash_screens/iPhone_16_Pro_portrait.png
  public/splash_screens/iPhone_16__iPhone_15_Pro__iPhone_15__iPhone_14_Pro_portrait.png
  public/splash_screens/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait.png
  public/splash_screens/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait.png
  public/splash_screens/icon.png
  public/vite.svg
  src/main.jsx
  src/routes/router.jsx
  yarn.lock
Labels: 🚀 Feat

#49 [feat] 카메라 페이지 구현
  src/api/customframes.js
  src/api/frames.js
  src/assets/svgs/Camera.svg
  src/assets/svgs/CameraButton.svg
  src/assets/svgs/Electronic.svg
  src/assets/svgs/Gallery.svg
  src/assets/svgs/Timer.svg
  src/components/common/BasicCameraFrame/index.jsx
  src/components/common/BasicFrame/index.jsx
  src/hooks/index.js
  src/hooks/useCameraFrames.js
  src/libraries/constants/FrameData.js
  src/libraries/reactQuery/ReactQuerySetting.jsx
  src/pages/Camera/CameraFrame/page.jsx
  src/pages/Camera/Download/page.jsx
  src/pages/CameraFrame/page.jsx
  src/pages/FrameCreate/Background/page.jsx
  src/pages/FrameCreate/page.jsx
  src/pages/FrameDetail/page.jsx
  src/pages/Main/page.jsx
  src/routes/routePath.js
  src/routes/router.jsx
Labels: 🎨 Design, 🚀 Feat

#50 [deploy] 서버 배포
  src/api/customframes.js
  src/api/frames.js
  src/assets/svgs/Camera.svg
  src/assets/svgs/CameraButton.svg
  src/assets/svgs/Electronic.svg
  src/assets/svgs/Gallery.svg
  src/assets/svgs/Timer.svg
  src/components/common/BasicCameraFrame/index.jsx
  src/components/common/BasicFrame/index.jsx
  src/hooks/index.js
  src/hooks/useCameraFrames.js
  src/libraries/constants/FrameData.js
  src/libraries/reactQuery/ReactQuerySetting.jsx
  src/pages/Camera/CameraFrame/page.jsx
  src/pages/Camera/Download/page.jsx
  src/pages/CameraFrame/page.jsx
  src/pages/FrameCreate/Background/page.jsx
  src/pages/FrameCreate/page.jsx
  src/pages/FrameDetail/page.jsx
  src/pages/Main/page.jsx
  src/routes/routePath.js
  src/routes/router.jsx
Labels: 🌎 Deploy

#53 [fix] 버셀 배포 오류 해결
  index.html
  jsconfig.json
  public/logo.svg
  src/App.jsx
  src/components/layout/Footer/index.jsx
  src/libraries/index.jsx
  src/routes/routePath.js
  src/routes/router.jsx
  vercel.json
  vite.config.js
Labels: 🔨 Fix

#54 [feat] 로그인, 회원가입 기능 구현
  package-lock.json
  package.json
  src/api/users.js
  src/pages/Auth/Login/page.jsx
  src/pages/Auth/Signup/page.jsx
  src/pages/LoginPage/index.css
  src/pages/LoginPage/page.jsx
  src/routes/routePath.js
  src/routes/router.jsx
  yarn.lock
Labels: 🚀 Feat

#56 [feat] 사진 생성 api 연동
  src/api/customframes.js
  src/api/index.js
  src/api/photos.js
  src/assets/svgs/CameraButton.svg
  src/components/common/BasicCameraFrame/index.jsx
  src/components/pages/Storage/GalleryImages/index.jsx
  src/libraries/reactQuery/ReactQuerySetting.jsx
  src/pages/Auth/Login/page.jsx
  src/pages/Auth/Signup/page.jsx
  src/pages/Camera/Download/page.jsx
  src/pages/FrameDetail/page.jsx
  src/pages/Main/page.jsx
  src/pages/Photo/Camera/page.jsx
  src/pages/Photo/Download/page.jsx
  src/routes/routePath.js
  src/routes/router.jsx
  src/test/PhotoCreateTestPage.jsx
Labels: 🎨 Design, 🚀 Feat

#58 [design] 카메라 크기 조절
  src/components/common/BasicCameraFrame/index.jsx
Labels: 🎨 Design

#60 [design] 디자인 수정
  src/api/photos.js
  src/components/common/BasicCameraFrame/index.jsx
  src/components/common/BasicFrame/index.jsx
  src/components/common/Button/IconButton/index.jsx
  src/components/layout/Footer/index.jsx
  src/components/layout/Header/index.jsx
  src/components/pages/Storage/GalleryImages/index.jsx
  src/components/pages/Storage/StorageLayout/index.jsx
  src/pages/Frame/Camera/page.jsx
  src/pages/Frame/Download/page.jsx
  src/pages/Frame/[id]/page.jsx
  src/pages/FrameCreate/Download/page.jsx
  src/pages/FrameCreate/Info/page.jsx
  src/pages/HotFrame/page.jsx
  src/pages/Main/page.jsx
  src/pages/Storage/Gallery/[id]/page.jsx
  src/routes/routePath.js
  src/routes/router.jsx
Labels: 🎨 Design, 🚀 Feat

#68 Feat/#52 sticker api
  package.json
  src/api/customframes.js
  src/api/index.js
  src/api/stickers.js
  src/components/pages/FrameCreate/EditPage/index.jsx
  src/components/pages/FrameCreate/Sticker/index.jsx
  src/libraries/store/storesticker.js
  src/pages/FrameCreate/Background/page.jsx
  src/pages/FrameCreate/Download/page.jsx
  src/pages/FrameCreate/Sticker/page.jsx
  src/pages/Storage/MyFrame/page.jsx
  src/routes/router.jsx
  src/test/CustomFrameCreateTestPage.jsx
  src/test/StickersTestPage.jsx
  yarn.lock
Labels: 🚀 Feat

#71 design: 헤더 디자인 수정
  src/components/pages/FrameCreate/EditPage/index.jsx
  src/components/pages/FrameCreate/PictureUploader/index.jsx
  src/pages/FrameCreate/Background/page.jsx
  src/pages/FrameCreate/Sticker/page.jsx
Labels: 🎨 Design, 🚀 Feat

#72 [design] 로그인 회원가입 기능 구현 및 수정
  src/pages/Auth/Login/page.jsx
  src/pages/Auth/Signup/page.jsx
Labels: 🎨 Design

#73 Feat/#69 sticker post api
  src/api/frames.js
  src/assets/svgs/delete.svg
  src/components/pages/FrameCreate/Sticker/index.jsx
  src/globals.css
  src/pages/FrameCreate/Sticker/page.jsx
  src/test/StickersTestPage.jsx
Labels: 🎨 Design, 🚀 Feat

#76 design: font 추가
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff2
  src/assets/Fonts/Pretendard-Bold.otf
  src/assets/Fonts/Pretendard-Bold.subset.woff
  src/assets/Fonts/Pretendard-Bold.subset.woff2
  src/assets/Fonts/Pretendard-Light.otf
  src/assets/Fonts/Pretendard-Medium.otf
  src/assets/Fonts/Pretendard-Medium.subset.woff
  src/assets/Fonts/Pretendard-Medium.subset.woff2
  src/assets/Fonts/Pretendard-Regular.subset.woff
  src/assets/Fonts/Pretendard-Regular.subset.woff2
  src/assets/Fonts/Pretendard-SemiBold.subset.woff
  src/assets/Fonts/Pretendard-SemiBold.subset.woff2
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-Light.woff2
  src/assets/fonts/Pretendard-Medium.woff2
  src/globals.css
Labels: 🎨 Design

#80 [fix] 흰 화면 오류 수정
  package.json
  src/pages/Frame/Camera/page.jsx
  src/pages/FrameCreate/Sticker/page.jsx
  src/pages/HotFrame/page.jsx
  src/pages/LatestFrame/page.jsx
  src/pages/Main/page.jsx
  yarn.lock
Labels: 🔨 Fix

#81 fix: html meta태그 및 스티커 생성
  index.html
  src/api/stickers.js
  src/components/pages/FrameCreate/PictureUploader/index.jsx
  src/pages/FrameCreate/Sticker/page.jsx
Labels: 🔨 Fix
